/*
 * Copyright (C) 2026 The pgvictoria community
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list
 * of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this
 * list of conditions and the following disclaimer in the documentation and/or other
 * materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may
 * be used to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef PG16_H_H
#define PG16_H_H

static const char* pg16_json =
   "{\n"
   "  \"allow_in_place_tablespaces\": \"off\",\n"
   "  \"allow_system_table_mods\": \"off\",\n"
   "  \"application_name\": \"psql\",\n"
   "  \"archive_cleanup_command\": \"\",\n"
   "  \"archive_command\": \"(disabled)\",\n"
   "  \"archive_library\": \"\",\n"
   "  \"archive_mode\": \"off\",\n"
   "  \"archive_timeout\": \"0\",\n"
   "  \"array_nulls\": \"on\",\n"
   "  \"authentication_timeout\": \"1min\",\n"
   "  \"autovacuum\": \"on\",\n"
   "  \"autovacuum_analyze_scale_factor\": \"0.1\",\n"
   "  \"autovacuum_analyze_threshold\": \"50\",\n"
   "  \"autovacuum_freeze_max_age\": \"200000000\",\n"
   "  \"autovacuum_max_workers\": \"3\",\n"
   "  \"autovacuum_multixact_freeze_max_age\": \"400000000\",\n"
   "  \"autovacuum_naptime\": \"1min\",\n"
   "  \"autovacuum_vacuum_cost_delay\": \"2ms\",\n"
   "  \"autovacuum_vacuum_cost_limit\": \"-1\",\n"
   "  \"autovacuum_vacuum_insert_scale_factor\": \"0.2\",\n"
   "  \"autovacuum_vacuum_insert_threshold\": \"1000\",\n"
   "  \"autovacuum_vacuum_scale_factor\": \"0.2\",\n"
   "  \"autovacuum_vacuum_threshold\": \"50\",\n"
   "  \"autovacuum_work_mem\": \"-1\",\n"
   "  \"backend_flush_after\": \"0\",\n"
   "  \"backslash_quote\": \"safe_encoding\",\n"
   "  \"backtrace_functions\": \"\",\n"
   "  \"bgwriter_delay\": \"200ms\",\n"
   "  \"bgwriter_flush_after\": \"512kB\",\n"
   "  \"bgwriter_lru_maxpages\": \"100\",\n"
   "  \"bgwriter_lru_multiplier\": \"2\",\n"
   "  \"block_size\": \"8192\",\n"
   "  \"bonjour\": \"off\",\n"
   "  \"bonjour_name\": \"\",\n"
   "  \"bytea_output\": \"hex\",\n"
   "  \"check_function_bodies\": \"on\",\n"
   "  \"checkpoint_completion_target\": \"0.9\",\n"
   "  \"checkpoint_flush_after\": \"256kB\",\n"
   "  \"checkpoint_timeout\": \"5min\",\n"
   "  \"checkpoint_warning\": \"30s\",\n"
   "  \"client_connection_check_interval\": \"0\",\n"
   "  \"client_encoding\": \"UTF8\",\n"
   "  \"client_min_messages\": \"notice\",\n"
   "  \"cluster_name\": \"\",\n"
   "  \"commit_delay\": \"0\",\n"
   "  \"commit_siblings\": \"5\",\n"
   "  \"compute_query_id\": \"auto\",\n"
   "  \"config_file\": \"/var/lib/postgresql/data/postgresql.conf\",\n"
   "  \"constraint_exclusion\": \"partition\",\n"
   "  \"cpu_index_tuple_cost\": \"0.005\",\n"
   "  \"cpu_operator_cost\": \"0.0025\",\n"
   "  \"createrole_self_grant\": \"\",\n"
   "  \"data_checksums\": \"off\",\n"
   "  \"data_directory\": \"/var/lib/postgresql/data\",\n"
   "  \"data_directory_mode\": \"0700\",\n"
   "  \"data_sync_retry\": \"off\",\n"
   "  \"DateStyle\": \"ISO, MDY\",\n"
   "  \"db_user_namespace\": \"off\",\n"
   "  \"deadlock_timeout\": \"1s\",\n"
   "  \"debug_assertions\": \"off\",\n"
   "  \"debug_discard_caches\": \"0\",\n"
   "  \"debug_io_direct\": \"\",\n"
   "  \"debug_logical_replication_streaming\": \"buffered\",\n"
   "  \"debug_parallel_query\": \"off\",\n"
   "  \"debug_pretty_print\": \"on\",\n"
   "  \"debug_print_parse\": \"off\",\n"
   "  \"debug_print_plan\": \"off\",\n"
   "  \"debug_print_rewritten\": \"off\",\n"
   "  \"default_statistics_target\": \"100\",\n"
   "  \"default_table_access_method\": \"heap\",\n"
   "  \"default_tablespace\": \"\",\n"
   "  \"default_text_search_config\": \"pg_catalog.english\",\n"
   "  \"default_toast_compression\": \"pglz\",\n"
   "  \"default_transaction_deferrable\": \"off\",\n"
   "  \"default_transaction_isolation\": \"read committed\",\n"
   "  \"default_transaction_read_only\": \"off\",\n"
   "  \"dynamic_library_path\": \"$libdir\",\n"
   "  \"dynamic_shared_memory_type\": \"posix\",\n"
   "  \"effective_cache_size\": \"4GB\",\n"
   "  \"effective_io_concurrency\": \"1\",\n"
   "  \"enable_async_append\": \"on\",\n"
   "  \"enable_bitmapscan\": \"on\",\n"
   "  \"enable_gathermerge\": \"on\",\n"
   "  \"enable_hashagg\": \"on\",\n"
   "  \"enable_hashjoin\": \"on\",\n"
   "  \"enable_incremental_sort\": \"on\",\n"
   "  \"enable_indexonlyscan\": \"on\",\n"
   "  \"enable_indexscan\": \"on\",\n"
   "  \"enable_material\": \"on\",\n"
   "  \"enable_memoize\": \"on\",\n"
   "  \"enable_mergejoin\": \"on\",\n"
   "  \"enable_nestloop\": \"on\",\n"
   "  \"enable_parallel_append\": \"on\",\n"
   "  \"enable_parallel_hash\": \"on\",\n"
   "  \"enable_partition_pruning\": \"on\",\n"
   "  \"enable_partitionwise_aggregate\": \"off\",\n"
   "  \"enable_partitionwise_join\": \"off\",\n"
   "  \"enable_presorted_aggregate\": \"on\",\n"
   "  \"enable_seqscan\": \"on\",\n"
   "  \"enable_sort\": \"on\",\n"
   "  \"enable_tidscan\": \"on\",\n"
   "  \"escape_string_warning\": \"on\",\n"
   "  \"event_source\": \"PostgreSQL\",\n"
   "  \"exit_on_error\": \"off\",\n"
   "  \"extension_destdir\": \"\",\n"
   "  \"external_pid_file\": \"\",\n"
   "  \"extra_float_digits\": \"1\",\n"
   "  \"file_extend_method\": \"posix_fallocate\",\n"
   "  \"from_collapse_limit\": \"8\",\n"
   "  \"fsync\": \"on\",\n"
   "  \"full_page_writes\": \"on\",\n"
   "  \"geqo\": \"on\",\n"
   "  \"geqo_effort\": \"5\",\n"
   "  \"geqo_generations\": \"0\",\n"
   "  \"geqo_pool_size\": \"0\",\n"
   "  \"geqo_seed\": \"0\",\n"
   "  \"geqo_selection_bias\": \"2\",\n"
   "  \"geqo_threshold\": \"12\",\n"
   "  \"gin_fuzzy_search_limit\": \"0\",\n"
   "  \"gin_pending_list_limit\": \"4MB\",\n"
   "  \"gss_accept_delegation\": \"off\",\n"
   "  \"hash_mem_multiplier\": \"2\",\n"
   "  \"hba_file\": \"/var/lib/postgresql/data/pg_hba.conf\",\n"
   "  \"hot_standby\": \"on\",\n"
   "  \"hot_standby_feedback\": \"off\",\n"
   "  \"huge_page_size\": \"0\",\n"
   "  \"huge_pages\": \"try\",\n"
   "  \"icu_validation_level\": \"warning\",\n"
   "  \"ident_file\": \"/var/lib/postgresql/data/pg_ident.conf\",\n"
   "  \"idle_in_transaction_session_timeout\": \"0\",\n"
   "  \"idle_session_timeout\": \"0\",\n"
   "  \"ignore_checksum_failure\": \"off\",\n"
   "  \"ignore_invalid_pages\": \"off\",\n"
   "  \"ignore_system_indexes\": \"off\",\n"
   "  \"in_hot_standby\": \"off\",\n"
   "  \"integer_datetimes\": \"on\",\n"
   "  \"IntervalStyle\": \"postgres\",\n"
   "  \"jit\": \"on\",\n"
   "  \"jit_above_cost\": \"100000\",\n"
   "  \"jit_debugging_support\": \"off\",\n"
   "  \"jit_dump_bitcode\": \"off\",\n"
   "  \"jit_expressions\": \"on\",\n"
   "  \"jit_inline_above_cost\": \"500000\",\n"
   "  \"jit_optimize_above_cost\": \"500000\",\n"
   "  \"jit_profiling_support\": \"off\",\n"
   "  \"jit_provider\": \"llvmjit\",\n"
   "  \"jit_tuple_deforming\": \"on\",\n"
   "  \"join_collapse_limit\": \"8\",\n"
   "  \"krb_caseins_users\": \"off\",\n"
   "  \"krb_server_keyfile\": \"FILE:/etc/postgresql-common/krb5.keytab\",\n"
   "  \"lc_messages\": \"en_US.utf8\",\n"
   "  \"lc_monetary\": \"en_US.utf8\",\n"
   "  \"lc_numeric\": \"en_US.utf8\",\n"
   "  \"lc_time\": \"en_US.utf8\",\n"
   "  \"listen_addresses\": \"*\",\n"
   "  \"lo_compat_privileges\": \"off\",\n"
   "  \"local_preload_libraries\": \"\",\n"
   "  \"lock_timeout\": \"0\",\n"
   "  \"log_autovacuum_min_duration\": \"10min\",\n"
   "  \"log_checkpoints\": \"on\",\n"
   "  \"log_connections\": \"off\",\n"
   "  \"log_destination\": \"stderr\",\n"
   "  \"log_directory\": \"log\",\n"
   "  \"log_disconnections\": \"off\",\n"
   "  \"log_duration\": \"off\",\n"
   "  \"log_error_verbosity\": \"default\",\n"
   "  \"log_executor_stats\": \"off\",\n"
   "  \"log_file_mode\": \"0600\",\n"
   "  \"log_filename\": \"postgresql-%Y-%m-%d_%H%M%S.log\",\n"
   "  \"log_hostname\": \"off\",\n"
   "  \"log_line_prefix\": \"%m [%p]\",\n"
   "  \"log_lock_waits\": \"off\",\n"
   "  \"log_min_duration_sample\": \"-1\",\n"
   "  \"log_min_duration_statement\": \"-1\",\n"
   "  \"log_min_error_statement\": \"error\",\n"
   "  \"log_min_messages\": \"warning\",\n"
   "  \"log_parameter_max_length\": \"-1\",\n"
   "  \"log_parameter_max_length_on_error\": \"0\",\n"
   "  \"log_parser_stats\": \"off\",\n"
   "  \"log_planner_stats\": \"off\",\n"
   "  \"log_recovery_conflict_waits\": \"off\",\n"
   "  \"log_replication_commands\": \"off\",\n"
   "  \"log_rotation_age\": \"1d\",\n"
   "  \"log_rotation_size\": \"10MB\",\n"
   "  \"log_startup_progress_interval\": \"10s\",\n"
   "  \"log_statement\": \"none\",\n"
   "  \"log_statement_sample_rate\": \"1\",\n"
   "  \"log_statement_stats\": \"off\",\n"
   "  \"log_temp_files\": \"-1\",\n"
   "  \"log_timezone\": \"Etc/UTC\",\n"
   "  \"log_transaction_sample_rate\": \"0\",\n"
   "  \"log_truncate_on_rotation\": \"off\",\n"
   "  \"logging_collector\": \"off\",\n"
   "  \"logical_decoding_work_mem\": \"64MB\",\n"
   "  \"maintenance_io_concurrency\": \"10\",\n"
   "  \"maintenance_work_mem\": \"64MB\",\n"
   "  \"max_connections\": \"100\",\n"
   "  \"max_files_per_process\": \"1000\",\n"
   "  \"max_function_args\": \"100\",\n"
   "  \"max_identifier_length\": \"63\",\n"
   "  \"max_index_keys\": \"32\",\n"
   "  \"max_locks_per_transaction\": \"64\",\n"
   "  \"max_logical_replication_workers\": \"4\",\n"
   "  \"max_parallel_apply_workers_per_subscription\": \"2\",\n"
   "  \"max_parallel_maintenance_workers\": \"2\",\n"
   "  \"max_parallel_workers\": \"8\",\n"
   "  \"max_parallel_workers_per_gather\": \"2\",\n"
   "  \"max_pred_locks_per_page\": \"2\",\n"
   "  \"max_pred_locks_per_relation\": \"-2\",\n"
   "  \"max_pred_locks_per_transaction\": \"64\",\n"
   "  \"max_prepared_transactions\": \"0\",\n"
   "  \"max_replication_slots\": \"10\",\n"
   "  \"max_slot_wal_keep_size\": \"-1\",\n"
   "  \"max_stack_depth\": \"2MB\",\n"
   "  \"max_standby_archive_delay\": \"30s\",\n"
   "  \"max_standby_streaming_delay\": \"30s\",\n"
   "  \"max_sync_workers_per_subscription\": \"2\",\n"
   "  \"max_wal_senders\": \"10\",\n"
   "  \"max_wal_size\": \"1GB\",\n"
   "  \"max_worker_processes\": \"8\",\n"
   "  \"min_dynamic_shared_memory\": \"0\",\n"
   "  \"min_parallel_index_scan_size\": \"512kB\",\n"
   "  \"min_parallel_table_scan_size\": \"8MB\",\n"
   "  \"min_wal_size\": \"80MB\",\n"
   "  \"old_snapshot_threshold\": \"-1\",\n"
   "  \"parallel_leader_participation\": \"on\",\n"
   "  \"parallel_setup_cost\": \"1000\",\n"
   "  \"password_encryption\": \"scram-sha-256\",\n"
   "  \"plan_cache_mode\": \"auto\",\n"
   "  \"port\": \"5432\",\n"
   "  \"post_auth_delay\": \"0\",\n"
   "  \"pre_auth_delay\": \"0\",\n"
   "  \"primary_conninfo\": \"\",\n"
   "  \"primary_slot_name\": \"\",\n"
   "  \"quote_all_identifiers\": \"off\",\n"
   "  \"random_page_cost\": \"4\",\n"
   "  \"recovery_end_command\": \"\",\n"
   "  \"recovery_init_sync_method\": \"fsync\",\n"
   "  \"recovery_min_apply_delay\": \"0\",\n"
   "  \"recovery_prefetch\": \"try\",\n"
   "  \"recovery_target\": \"\",\n"
   "  \"recovery_target_action\": \"pause\",\n"
   "  \"recovery_target_inclusive\": \"on\",\n"
   "  \"recovery_target_lsn\": \"\",\n"
   "  \"recovery_target_name\": \"\",\n"
   "  \"recovery_target_time\": \"\",\n"
   "  \"recovery_target_timeline\": \"latest\",\n"
   "  \"recovery_target_xid\": \"\",\n"
   "  \"recursive_worktable_factor\": \"10\",\n"
   "  \"remove_temp_files_after_crash\": \"on\",\n"
   "  \"reserved_connections\": \"0\",\n"
   "  \"restart_after_crash\": \"on\",\n"
   "  \"restore_command\": \"\",\n"
   "  \"restrict_nonsystem_relation_kind\": \"\",\n"
   "  \"scram_iterations\": \"4096\",\n"
   "  \"search_path\": \"\\\"$user\\\", public\",\n"
   "  \"segment_size\": \"1GB\",\n"
   "  \"send_abort_for_crash\": \"off\",\n"
   "  \"send_abort_for_kill\": \"off\",\n"
   "  \"seq_page_cost\": \"1\",\n"
   "  \"server_encoding\": \"UTF8\",\n"
   "  \"server_version\": \"16.13 (Debian 16.13-1.pgdg13+1)\",\n"
   "  \"server_version_num\": \"160013\",\n"
   "  \"session_preload_libraries\": \"\",\n"
   "  \"session_replication_role\": \"origin\",\n"
   "  \"shared_buffers\": \"128MB\",\n"
   "  \"shared_memory_size\": \"143MB\",\n"
   "  \"shared_memory_size_in_huge_pages\": \"72\",\n"
   "  \"shared_memory_type\": \"mmap\",\n"
   "  \"shared_preload_libraries\": \"\",\n"
   "  \"ssl\": \"off\",\n"
   "  \"ssl_ca_file\": \"\",\n"
   "  \"ssl_cert_file\": \"server.crt\",\n"
   "  \"ssl_ciphers\": \"HIGH:MEDIUM:+3DES:!aNULL\",\n"
   "  \"ssl_crl_dir\": \"\",\n"
   "  \"ssl_crl_file\": \"\",\n"
   "  \"ssl_dh_params_file\": \"\",\n"
   "  \"ssl_ecdh_curve\": \"prime256v1\",\n"
   "  \"ssl_key_file\": \"server.key\",\n"
   "  \"ssl_library\": \"OpenSSL\",\n"
   "  \"ssl_max_protocol_version\": \"\",\n"
   "  \"ssl_min_protocol_version\": \"TLSv1.2\",\n"
   "  \"ssl_passphrase_command\": \"\",\n"
   "  \"ssl_passphrase_command_supports_reload\": \"off\",\n"
   "  \"ssl_prefer_server_ciphers\": \"on\",\n"
   "  \"standard_conforming_strings\": \"on\",\n"
   "  \"statement_timeout\": \"0\",\n"
   "  \"stats_fetch_consistency\": \"cache\",\n"
   "  \"superuser_reserved_connections\": \"3\",\n"
   "  \"synchronize_seqscans\": \"on\",\n"
   "  \"synchronous_commit\": \"on\",\n"
   "  \"synchronous_standby_names\": \"\",\n"
   "  \"syslog_facility\": \"local0\",\n"
   "  \"syslog_ident\": \"postgres\",\n"
   "  \"syslog_sequence_numbers\": \"on\",\n"
   "  \"syslog_split_messages\": \"on\",\n"
   "  \"tcp_keepalives_count\": \"0\",\n"
   "  \"tcp_keepalives_idle\": \"0\",\n"
   "  \"tcp_keepalives_interval\": \"0\",\n"
   "  \"tcp_user_timeout\": \"0\",\n"
   "  \"temp_buffers\": \"8MB\",\n"
   "  \"temp_file_limit\": \"-1\",\n"
   "  \"temp_tablespaces\": \"\",\n"
   "  \"TimeZone\": \"Etc/UTC\",\n"
   "  \"timezone_abbreviations\": \"Default\",\n"
   "  \"trace_notify\": \"off\",\n"
   "  \"trace_recovery_messages\": \"log\",\n"
   "  \"trace_sort\": \"off\",\n"
   "  \"track_activities\": \"on\",\n"
   "  \"track_activity_query_size\": \"1kB\",\n"
   "  \"track_commit_timestamp\": \"off\",\n"
   "  \"track_counts\": \"on\",\n"
   "  \"track_functions\": \"none\",\n"
   "  \"track_io_timing\": \"off\",\n"
   "  \"track_wal_io_timing\": \"off\",\n"
   "  \"transaction_deferrable\": \"off\",\n"
   "  \"transaction_isolation\": \"read committed\",\n"
   "  \"transaction_read_only\": \"off\",\n"
   "  \"transform_null_equals\": \"off\",\n"
   "  \"unix_socket_directories\": \"/var/run/postgresql\",\n"
   "  \"unix_socket_group\": \"\",\n"
   "  \"unix_socket_permissions\": \"0777\",\n"
   "  \"update_process_title\": \"on\",\n"
   "  \"vacuum_buffer_usage_limit\": \"256kB\",\n"
   "  \"vacuum_cost_delay\": \"0\",\n"
   "  \"vacuum_cost_limit\": \"200\",\n"
   "  \"vacuum_cost_page_dirty\": \"20\",\n"
   "  \"vacuum_cost_page_hit\": \"1\",\n"
   "  \"vacuum_cost_page_miss\": \"2\",\n"
   "  \"vacuum_failsafe_age\": \"1600000000\",\n"
   "  \"vacuum_freeze_table_age\": \"150000000\",\n"
   "  \"vacuum_multixact_failsafe_age\": \"1600000000\",\n"
   "  \"vacuum_multixact_freeze_table_age\": \"150000000\",\n"
   "  \"wal_block_size\": \"8192\",\n"
   "  \"wal_buffers\": \"4MB\",\n"
   "  \"wal_compression\": \"off\",\n"
   "  \"wal_consistency_checking\": \"\",\n"
   "  \"wal_decode_buffer_size\": \"512kB\",\n"
   "  \"wal_init_zero\": \"on\",\n"
   "  \"wal_keep_size\": \"0\",\n"
   "  \"wal_level\": \"replica\",\n"
   "  \"wal_log_hints\": \"off\",\n"
   "  \"wal_receiver_create_temp_slot\": \"off\",\n"
   "  \"wal_receiver_status_interval\": \"10s\",\n"
   "  \"wal_receiver_timeout\": \"1min\",\n"
   "  \"wal_recycle\": \"on\",\n"
   "  \"wal_retrieve_retry_interval\": \"5s\",\n"
   "  \"wal_segment_size\": \"16MB\",\n"
   "  \"wal_sender_timeout\": \"1min\",\n"
   "  \"wal_skip_threshold\": \"2MB\",\n"
   "  \"wal_sync_method\": \"fdatasync\",\n"
   "  \"wal_writer_delay\": \"200ms\",\n"
   "  \"wal_writer_flush_after\": \"1MB\",\n"
   "  \"work_mem\": \"4MB\",\n"
   "  \"xmlbinary\": \"base64\",\n"
   "  \"xmloption\": \"content\",\n"
   "  \"zero_damaged_pages\": \"off\"\n"
   "}";

#endif
